name: Hello world workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: says hello
        run: echo "Hello World!"
      - name: print the date
        run: date
      - name: print directory contents
        run: ls -l
